import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react';
import dompurify from "dompurify";
import styles from "styles/main.module.css"

export default function Home () {

  const [getNotice,setNotice] = useState<{[key:string]:any}[]>([]);
  useEffect(()=>{
    const fetchData = async ()=>{
      const noticeList:{[key:string]:any}[] = [];
      const getRecent = await axios.get("/api/recent");
      const recent = Number(await getRecent.data.recent);
      for(let i=recent; i>=(recent-50); i--){
        const content = await axios.get(`/api/notice_id=${i}`)
        setTimeout(()=>{
          noticeList.push(content.data);
        },100)
        setNotice(noticeList.filter(el=>el.title.trim()))
      }
    }
    fetchData()
  },[])
  

  return (
    <>
      <Head>
        <title>넓은마을 공지사항</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>넓은마을 공지사항</h1>
        <nav><ul><li><a href="http://web.kbuwel.or.kr">넓은 마을로 이동</a></li></ul></nav>
      </header>
      <main className={styles.main}>
        {
          getNotice.map((n,idx)=>{
            return (
              <article className={styles.notice} key={idx}>
                <div className={styles.title}>
                  <h2>{n.title}</h2>
                  <p className={styles.date}><b>{n.date}</b></p>
                </div>
                <div className={styles.content} dangerouslySetInnerHTML={{__html: dompurify.sanitize(n.content
                    .replaceAll(/(.+\n)/g,"<p> $1 </p>")
                    .replaceAll("<br>","\n")
                    .replaceAll(/([0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3})/g,"<a href=\"mailto:$1\">$1</a>")
                    .replaceAll(/(\d{3,4}(-\d{3,4}){1,2})/g,"<a href=\"tel:$1\" title=\"전화걸기\">$1</a>")
                  )}}>
                </div>
              </article>
            )
          })
        }
      </main>
      <footer>
        <p>
          &copy; 2023 Ungjin Park. Powered by <a href="http://web.kbuwel.or.kr">web.kbuwel.or.kr</a>
        </p>
      </footer>
    </>
  )
}