import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react';
import dompurify from "dompurify";
import styles from "styles/main.module.css"
export default function Home () {

  const [getNotice,setNotice] = useState<{[key:string]:any}[]>([]);
  useEffect(()=>{
    const fetchData = async ()=>{
      const noticeList:{[key:string]:any}[] = [];
      const getRecent = await axios.get("/api/recent");
      const recent = Number(await getRecent.data.recent);
      for(let i=recent; i>=(recent-50); i--){
        const content = await axios.get(`/api/notice_id=${i}`)
        setTimeout(()=>{
          noticeList.push(content.data);
        },100)
        setNotice(noticeList)
      }
    }
    fetchData()
  },[])
  

  return (
    <>
      <Head>
        <title>넓은마을 공지사항 PARSET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>넓은마을 공지사항</h1>
      </header>
      <main className={styles.main}>
        {
          getNotice.map((n,idx)=>{
            return (
              <article className={styles.notice} key={idx}>
                <div className={styles.title}>
                  <h2>{n.title}</h2>
                  <p className={styles.date}><b>{n.date}</b></p>
                </div>
                <div className={styles.content}
                dangerouslySetInnerHTML={{__html:dompurify.sanitize(n.content)}}>
                </div>
              </article>
            )
          })
        }
      </main>
    </>
  )
}